server:
  port: 8080
  contextPath: /newsletterSub
  endPointPath: endpoints
  basePath: http://localhost
  error:
      path: /error
      whitelabel:
          enabled: false
  ssl:
    enabled: false
    key-store: classpath:main.jks
    key-password: secret

#quartz:
#    enabled: true

management:
    context-path: /manage
    port: 8081
    ssl:
        enabled: false
        key-store: classpath:management.jks
        key-password: secret
    address: 127.0.0.1
    security:
        enabled: true
        roles: EPADMIN
    info:
        git:
            mode: full
#security:
#    user:
#        name: epadmin
#        password: epadmin
#    basic:
#        enabled: true
endpoints:
    sensitive: true
    metrics:
        id: app_metrics
    health:
        id: app_health
    beans:
        id: app_beans
    info:
        id: app_info
    shutdown:
        enabled: true
---
spring:
  profiles: prod
  resources:
    #staticLocations: classpath:/static/
    #cachePeriod: 0
  application:
      name: REST API newsletter subscription
      thymeleaf:
          cache: false
          enabled: true
          prefix: classpath:/templates/
          suffix: .html
          checkTemplateLocation: true
          mode: LEGACYHTML5
          encoding: UTF-8
          contentType: text/html
  main:
      banner-mode: "off"
  #mail:
  #    host: localhost
  #    port: 25
  #    protocol: smtp
  #    defaultEncoding: UTF-8
datasource:
  subscriptionapp:
    url: jdbc:h2:~/subscriptiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl:
        method: create-drop
        import_files: subscriptiondb_dml.sql
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      globally_quoted_identifiers: true
      connection:
          characterEncoding: UTF-8
          charSet: UTF-8
          useUnicode: true
---
spring:
  profiles: local, default
  resources:
    #staticLocations: classpath:/static/
    #cachePeriod: 0
  metrics:
    export:
        enabled: false
        redis:
            prefix: metrics.newsletterSub.${spring.application.name:application}.${random.value:0000}
            key: keys.metrics.newsletterSub
  application:
      name: REST API newsletter subscription
      thymeleaf:
          cache: false
          enabled: true
          prefix: classpath:/templates/
          suffix: .html
          checkTemplateLocation: true
          mode: LEGACYHTML5
          encoding: UTF-8
          contentType: text/html
  jackson:
    serialization:
        write_dates_as_timestamps: false
  main:
      banner-mode: "console"
  #mail:
  #    host: localhost
  #    port: 25
  #    protocol: smtp
  #    defaultEncoding: UTF-8
datasource:
  subscriptionapp:
    url: jdbc:mysql://localhost:3306/subscriptiondb?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: toor
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    minPoolSize: 5
    maxStatements: 100
    maxStatementsPerConnection: 20
    acquire_increment: 5
    use_sql_comments: true
    hibernate:
      hbm2ddl:
        method: create-drop
        import_files: subscriptiondb_dml.sql
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      globally_quoted_identifiers: true
      cache:
        use_second_level_cache: false
        use_query_cache: false
      connection:
        characterEncoding: UTF-8
        charSet: UTF-8
        useUnicode: true
---
logging:
    level:
        org:
            springframework:
                web: INFO
            hibernate: INFO
            