server:
  port: 8080
  contextPath: /rest
---
spring:
  profiles: prod
datasource:
  subscriptionapp:
    url: jdbc:h2:~/subscriptiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      globally_quoted_identifiers: true
---
spring:
  profiles: local, default
datasource:
  subscriptionapp:
    url: jdbc:mysql://localhost:3306/subscriptiondb?createDatabaseIfNotExist=true
    username: root
    password: toor
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      globally_quoted_identifiers: true